/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AltaRouteImport } from './routes/alta'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAvisosRouteImport } from './routes/_authenticated/avisos'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedEmpresaRouteImport } from './routes/_authenticated/empresa'
import { Route as AuthenticatedEmpresaNuevaRouteImport } from './routes/_authenticated/empresa-nueva'
import { Route as AuthenticatedInformesRouteImport } from './routes/_authenticated/informes'
import { Route as AuthenticatedPrevencionRouteImport } from './routes/_authenticated/prevencion'
import { Route as AuthenticatedSuperadminRouteImport } from './routes/_authenticated/superadmin'
import { Route as AuthenticatedTutorialRouteImport } from './routes/_authenticated/tutorial'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedBorradoresIdRouteImport } from './routes/_authenticated/borradores.$id'
import { Route as AuthenticatedConductoresIndexRouteImport } from './routes/_authenticated/conductores.index'
import { Route as AuthenticatedConductoresIdRouteImport } from './routes/_authenticated/conductores.$id'
import { Route as AuthenticatedSancionesIndexRouteImport } from './routes/_authenticated/sanciones.index'
import { Route as AuthenticatedSancionesIdRouteImport } from './routes/_authenticated/sanciones.$id'
import { Route as AuthenticatedSancionesNuevaRouteImport } from './routes/_authenticated/sanciones.nueva'
import { Route as AuthenticatedVehiculosIndexRouteImport } from './routes/_authenticated/vehiculos.index'
import { Route as AuthenticatedVehiculosIdRouteImport } from './routes/_authenticated/vehiculos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AltaRoute = AltaRouteImport.update({
  id: '/alta',
  path: '/alta',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAvisosRoute = AuthenticatedAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresaRoute = AuthenticatedEmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresaNuevaRoute =
  AuthenticatedEmpresaNuevaRouteImport.update({
    id: '/empresa-nueva',
    path: '/empresa-nueva',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInformesRoute = AuthenticatedInformesRouteImport.update({
  id: '/informes',
  path: '/informes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrevencionRoute = AuthenticatedPrevencionRouteImport.update({
  id: '/prevencion',
  path: '/prevencion',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuperadminRoute = AuthenticatedSuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTutorialRoute = AuthenticatedTutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBorradoresIdRoute =
  AuthenticatedBorradoresIdRouteImport.update({
    id: '/borradores/$id',
    path: '/borradores/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConductoresIndexRoute =
  AuthenticatedConductoresIndexRouteImport.update({
    id: '/conductores/',
    path: '/conductores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConductoresIdRoute =
  AuthenticatedConductoresIdRouteImport.update({
    id: '/conductores/$id',
    path: '/conductores/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSancionesIndexRoute =
  AuthenticatedSancionesIndexRouteImport.update({
    id: '/sanciones/',
    path: '/sanciones/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSancionesIdRoute =
  AuthenticatedSancionesIdRouteImport.update({
    id: '/sanciones/$id',
    path: '/sanciones/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSancionesNuevaRoute =
  AuthenticatedSancionesNuevaRouteImport.update({
    id: '/sanciones/nueva',
    path: '/sanciones/nueva',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVehiculosIndexRoute =
  AuthenticatedVehiculosIndexRouteImport.update({
    id: '/vehiculos/',
    path: '/vehiculos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVehiculosIdRoute =
  AuthenticatedVehiculosIdRouteImport.update({
    id: '/vehiculos/$id',
    path: '/vehiculos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alta': typeof AltaRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/avisos': typeof AuthenticatedAvisosRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/empresa': typeof AuthenticatedEmpresaRoute
  '/empresa-nueva': typeof AuthenticatedEmpresaNuevaRoute
  '/informes': typeof AuthenticatedInformesRoute
  '/prevencion': typeof AuthenticatedPrevencionRoute
  '/superadmin': typeof AuthenticatedSuperadminRoute
  '/tutorial': typeof AuthenticatedTutorialRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/borradores/$id': typeof AuthenticatedBorradoresIdRoute
  '/conductores/$id': typeof AuthenticatedConductoresIdRoute
  '/sanciones/$id': typeof AuthenticatedSancionesIdRoute
  '/sanciones/nueva': typeof AuthenticatedSancionesNuevaRoute
  '/vehiculos/$id': typeof AuthenticatedVehiculosIdRoute
  '/conductores/': typeof AuthenticatedConductoresIndexRoute
  '/sanciones/': typeof AuthenticatedSancionesIndexRoute
  '/vehiculos/': typeof AuthenticatedVehiculosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alta': typeof AltaRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/avisos': typeof AuthenticatedAvisosRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/empresa': typeof AuthenticatedEmpresaRoute
  '/empresa-nueva': typeof AuthenticatedEmpresaNuevaRoute
  '/informes': typeof AuthenticatedInformesRoute
  '/prevencion': typeof AuthenticatedPrevencionRoute
  '/superadmin': typeof AuthenticatedSuperadminRoute
  '/tutorial': typeof AuthenticatedTutorialRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/borradores/$id': typeof AuthenticatedBorradoresIdRoute
  '/conductores/$id': typeof AuthenticatedConductoresIdRoute
  '/sanciones/$id': typeof AuthenticatedSancionesIdRoute
  '/sanciones/nueva': typeof AuthenticatedSancionesNuevaRoute
  '/vehiculos/$id': typeof AuthenticatedVehiculosIdRoute
  '/conductores': typeof AuthenticatedConductoresIndexRoute
  '/sanciones': typeof AuthenticatedSancionesIndexRoute
  '/vehiculos': typeof AuthenticatedVehiculosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/alta': typeof AltaRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/avisos': typeof AuthenticatedAvisosRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/empresa': typeof AuthenticatedEmpresaRoute
  '/_authenticated/empresa-nueva': typeof AuthenticatedEmpresaNuevaRoute
  '/_authenticated/informes': typeof AuthenticatedInformesRoute
  '/_authenticated/prevencion': typeof AuthenticatedPrevencionRoute
  '/_authenticated/superadmin': typeof AuthenticatedSuperadminRoute
  '/_authenticated/tutorial': typeof AuthenticatedTutorialRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/borradores/$id': typeof AuthenticatedBorradoresIdRoute
  '/_authenticated/conductores/$id': typeof AuthenticatedConductoresIdRoute
  '/_authenticated/sanciones/$id': typeof AuthenticatedSancionesIdRoute
  '/_authenticated/sanciones/nueva': typeof AuthenticatedSancionesNuevaRoute
  '/_authenticated/vehiculos/$id': typeof AuthenticatedVehiculosIdRoute
  '/_authenticated/conductores/': typeof AuthenticatedConductoresIndexRoute
  '/_authenticated/sanciones/': typeof AuthenticatedSancionesIndexRoute
  '/_authenticated/vehiculos/': typeof AuthenticatedVehiculosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alta'
    | '/auth'
    | '/reset-password'
    | '/avisos'
    | '/calendario'
    | '/dashboard'
    | '/documentos'
    | '/empresa'
    | '/empresa-nueva'
    | '/informes'
    | '/prevencion'
    | '/superadmin'
    | '/tutorial'
    | '/usuarios'
    | '/borradores/$id'
    | '/conductores/$id'
    | '/sanciones/$id'
    | '/sanciones/nueva'
    | '/vehiculos/$id'
    | '/conductores/'
    | '/sanciones/'
    | '/vehiculos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alta'
    | '/auth'
    | '/reset-password'
    | '/avisos'
    | '/calendario'
    | '/dashboard'
    | '/documentos'
    | '/empresa'
    | '/empresa-nueva'
    | '/informes'
    | '/prevencion'
    | '/superadmin'
    | '/tutorial'
    | '/usuarios'
    | '/borradores/$id'
    | '/conductores/$id'
    | '/sanciones/$id'
    | '/sanciones/nueva'
    | '/vehiculos/$id'
    | '/conductores'
    | '/sanciones'
    | '/vehiculos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/alta'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/avisos'
    | '/_authenticated/calendario'
    | '/_authenticated/dashboard'
    | '/_authenticated/documentos'
    | '/_authenticated/empresa'
    | '/_authenticated/empresa-nueva'
    | '/_authenticated/informes'
    | '/_authenticated/prevencion'
    | '/_authenticated/superadmin'
    | '/_authenticated/tutorial'
    | '/_authenticated/usuarios'
    | '/_authenticated/borradores/$id'
    | '/_authenticated/conductores/$id'
    | '/_authenticated/sanciones/$id'
    | '/_authenticated/sanciones/nueva'
    | '/_authenticated/vehiculos/$id'
    | '/_authenticated/conductores/'
    | '/_authenticated/sanciones/'
    | '/_authenticated/vehiculos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AltaRoute: typeof AltaRoute
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alta': {
      id: '/alta'
      path: '/alta'
      fullPath: '/alta'
      preLoaderRoute: typeof AltaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/avisos': {
      id: '/_authenticated/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AuthenticatedAvisosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresa': {
      id: '/_authenticated/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof AuthenticatedEmpresaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresa-nueva': {
      id: '/_authenticated/empresa-nueva'
      path: '/empresa-nueva'
      fullPath: '/empresa-nueva'
      preLoaderRoute: typeof AuthenticatedEmpresaNuevaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/informes': {
      id: '/_authenticated/informes'
      path: '/informes'
      fullPath: '/informes'
      preLoaderRoute: typeof AuthenticatedInformesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prevencion': {
      id: '/_authenticated/prevencion'
      path: '/prevencion'
      fullPath: '/prevencion'
      preLoaderRoute: typeof AuthenticatedPrevencionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/superadmin': {
      id: '/_authenticated/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof AuthenticatedSuperadminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tutorial': {
      id: '/_authenticated/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof AuthenticatedTutorialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/borradores/$id': {
      id: '/_authenticated/borradores/$id'
      path: '/borradores/$id'
      fullPath: '/borradores/$id'
      preLoaderRoute: typeof AuthenticatedBorradoresIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conductores/': {
      id: '/_authenticated/conductores/'
      path: '/conductores'
      fullPath: '/conductores/'
      preLoaderRoute: typeof AuthenticatedConductoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conductores/$id': {
      id: '/_authenticated/conductores/$id'
      path: '/conductores/$id'
      fullPath: '/conductores/$id'
      preLoaderRoute: typeof AuthenticatedConductoresIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sanciones/': {
      id: '/_authenticated/sanciones/'
      path: '/sanciones'
      fullPath: '/sanciones/'
      preLoaderRoute: typeof AuthenticatedSancionesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sanciones/$id': {
      id: '/_authenticated/sanciones/$id'
      path: '/sanciones/$id'
      fullPath: '/sanciones/$id'
      preLoaderRoute: typeof AuthenticatedSancionesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sanciones/nueva': {
      id: '/_authenticated/sanciones/nueva'
      path: '/sanciones/nueva'
      fullPath: '/sanciones/nueva'
      preLoaderRoute: typeof AuthenticatedSancionesNuevaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vehiculos/': {
      id: '/_authenticated/vehiculos/'
      path: '/vehiculos'
      fullPath: '/vehiculos/'
      preLoaderRoute: typeof AuthenticatedVehiculosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vehiculos/$id': {
      id: '/_authenticated/vehiculos/$id'
      path: '/vehiculos/$id'
      fullPath: '/vehiculos/$id'
      preLoaderRoute: typeof AuthenticatedVehiculosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAvisosRoute: typeof AuthenticatedAvisosRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedEmpresaRoute: typeof AuthenticatedEmpresaRoute
  AuthenticatedEmpresaNuevaRoute: typeof AuthenticatedEmpresaNuevaRoute
  AuthenticatedInformesRoute: typeof AuthenticatedInformesRoute
  AuthenticatedPrevencionRoute: typeof AuthenticatedPrevencionRoute
  AuthenticatedSuperadminRoute: typeof AuthenticatedSuperadminRoute
  AuthenticatedTutorialRoute: typeof AuthenticatedTutorialRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedBorradoresIdRoute: typeof AuthenticatedBorradoresIdRoute
  AuthenticatedConductoresIdRoute: typeof AuthenticatedConductoresIdRoute
  AuthenticatedSancionesIdRoute: typeof AuthenticatedSancionesIdRoute
  AuthenticatedSancionesNuevaRoute: typeof AuthenticatedSancionesNuevaRoute
  AuthenticatedVehiculosIdRoute: typeof AuthenticatedVehiculosIdRoute
  AuthenticatedConductoresIndexRoute: typeof AuthenticatedConductoresIndexRoute
  AuthenticatedSancionesIndexRoute: typeof AuthenticatedSancionesIndexRoute
  AuthenticatedVehiculosIndexRoute: typeof AuthenticatedVehiculosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAvisosRoute: AuthenticatedAvisosRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedEmpresaRoute: AuthenticatedEmpresaRoute,
  AuthenticatedEmpresaNuevaRoute: AuthenticatedEmpresaNuevaRoute,
  AuthenticatedInformesRoute: AuthenticatedInformesRoute,
  AuthenticatedPrevencionRoute: AuthenticatedPrevencionRoute,
  AuthenticatedSuperadminRoute: AuthenticatedSuperadminRoute,
  AuthenticatedTutorialRoute: AuthenticatedTutorialRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedBorradoresIdRoute: AuthenticatedBorradoresIdRoute,
  AuthenticatedConductoresIdRoute: AuthenticatedConductoresIdRoute,
  AuthenticatedSancionesIdRoute: AuthenticatedSancionesIdRoute,
  AuthenticatedSancionesNuevaRoute: AuthenticatedSancionesNuevaRoute,
  AuthenticatedVehiculosIdRoute: AuthenticatedVehiculosIdRoute,
  AuthenticatedConductoresIndexRoute: AuthenticatedConductoresIndexRoute,
  AuthenticatedSancionesIndexRoute: AuthenticatedSancionesIndexRoute,
  AuthenticatedVehiculosIndexRoute: AuthenticatedVehiculosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AltaRoute: AltaRoute,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
